// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmuiqnquarophbtpvoyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtdWlxbnF1YXJvcGhidHB2b3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzQyMjcsImV4cCI6MjA2Nzk1MDIyN30.jqbgYmdok7fzucMUXBt0WBq6ASDypiqjrY_vm2I2CaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});